### ISSUE TITLE
app.js

### ISSUE THREAD

**Issue by RedizGaming** [kudo070/opencase#3]
APP.JS error (node app.js)

and this doesn't have roll animation?

/var/www/html/app.js:24
, {online: Object.keys(io.sockets.adapter.rooms).length, games: stat.games, us
                                                                    ^
TypeError: Cannot read property 'games' of null
    at Command.callback (/var/www/html/app.js:24:92)
    at normal_reply (/var/www/html/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/var/www/html/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.Parser.returnReply (/var/www/html/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/var/www/html/node_modules/redis/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/var/www/html/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by kudo070** [comment]
var stats = function () {
    serv.get('stats', (err, data)  => {
       if(err || data == null) return;
        var stat = JSON.parse(data);
        io.emit('stats', {online: Object.keys(io.sockets.adapter.rooms).length, games: stat.games, users: stat.users});
    })
};

**Comment by RedizGaming** [comment]
node app.js
/var/www/html/app.js:22
serv.get('stats', (err, data) => {
                              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


----

removing " =>"

 node app.js
/var/www/html/app.js:22
serv.get('stats', (err, data) {
                              ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by xAgentXx** [comment]
How i can fix this:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'csgo.games' doesn't exist

#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT items....', Array, Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
#4 /var/www/html/case/app/config/services.php(226): Phalcon\Mvc\Model\Query->execute()
#5 [internal function]: Closure->{closure}()
#6 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#7 /var/www/html/case/app/config/services.php(48): Phalcon\Di->get('winners')
#8 [internal function]: Closure->{closure}()
#9 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#10 [internal function]: Phalcon\Di->get('view', NULL)
#11 [internal function]: Phalcon\Di->getShared('view')
#12 /var/www/html/case/public/index.php(40): Phalcon\Mvc\Application->handle()
#13 {main}

Sorry For this english i am from Germany.

**Comment by kudo070** [comment]
Update Node JS

The script supports node v7.8.0

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by RedizGaming** [comment]
node app.js

![image](https://cloud.githubusercontent.com/assets/27127261/24841337/c0022f00-1d58-11e7-8c23-d5ff0e0f7d2d.png)

**Comment by RedizGaming** [comment]
const io = require('socket.io')(7777);
const redis = require('redis');
const client = redis.createClient();
const serv = redis.createClient();

client.subscribe('winners');
client.setMaxListeners(0);
client.on('message', function (channel, message) {
    stats();
    io.emit(channel, message);
});


io.on('connection', function (socket) {
    stats();
    socket.on('disconnect', function () {
        stats();
    });
});

var stats = function () {
serv.get('stats', (err, data) => {
if(err || data == null) return;
var stat = JSON.parse(data);
io.emit('stats', {online: Object.keys(io.sockets.adapter.rooms).length, games: stat.games, users: stat.users});
})
};
