### ISSUE TITLE
app.js error - and ¿why open cases doesn't have animation??

### ISSUE THREAD

**Issue by RedizGaming** [kudo070/opencase#5]
node app.js
/var/www/html/app.js:22
serv.get('stats', (err, data) => {
^^
SyntaxError: Unexpected token =>
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

removing " =>"

node app.js
/var/www/html/app.js:22
serv.get('stats', (err, data) {
^
SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

**Comment by RedizGaming** [comment]
edited and get this error

 node app.js
/var/www/html/app.js:24
, {online: Object.keys(io.sockets.adapter.rooms).length, games: stat.game, use
                                                                    ^
TypeError: Cannot read property 'game' of null
    at Command.callback (/var/www/html/app.js:24:92)
    at normal_reply (/var/www/html/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/var/www/html/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.Parser.returnReply (/var/www/html/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/var/www/html/node_modules/redis/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/var/www/html/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by kudo070** [comment]
https://github.com/kudo070/opencase/commit/8f858a2b213b966cede9106be659df099495ff6c

**Comment by xAgentXx** [comment]
/var/www/html/app.js:8
client.on('message', (channel, message) => {
                                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

With your new App.js

**Comment by RedizGaming** [comment]
/var/www/html/app.js:22
data:    app.js:3036 -       serv.get('stats', (err, data) => {
data:    app.js:3036 -                                     ^^
data:    app.js:3036 - SyntaxError: Unexpected token =>
data:    app.js:3036 -     at exports.runInThisContext (vm.js:73:16)
data:    app.js:3036 -     at Module._compile (module.js:443:25)
data:    app.js:3036 -     at Object.Module._extensions..js (module.js:478:10)
data:    app.js:3036 -     at Module.load (module.js:355:32)
data:    app.js:3036 -     at Function.Module._load (module.js:310:12)
data:    app.js:3036 -     at Function.Module.runMain (module.js:501:10)
data:    app.js:3036 -     at startup (node.js:129:16)
data:    app.js:3036 -     at node.js:814:3

i write this.
